
services:
    caddy:
        image: caddy:2.4.5
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/site:/srv
            - $PWD/elec_site:/elec_site
            - $PWD/html:/srvviewer
            - /home/tart/ops/object_position_server/app/doc:/doc
            - caddy_data:/data
            - caddy_config:/config

        extra_hosts:
            - "host.docker.internal:172.17.0.1"
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"


    viewer:
        image: ghcr.io/tart-telescope/web_app/viewer-subpath:sha-95f3a7e-amd64

volumes:
    caddy_data:
        external: true
    caddy_config:

