services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    volumes:
      - ./src:/usr/src/app/src
      - ./img:/usr/src/app/img
